update

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -1,9 +1,13 @@
 name: GitHub Actions Demo
 run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
+
 on:
-    push:
-        paths:
-            - '**/hello.html' # Watches for changes to hello.html at the root level
+  push:
+    branches:
+      - main
+    paths:
+      - 'hello.html' # Watches for changes to hello.html at the root level
+
 jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-latest
@@ -20,19 +24,16 @@ jobs:
           ls ${{ github.workspace }}
       - name: Check if hello.html exists
         run: |
-            if [ -f "hello.html" ]; then
-              echo "✅ hello.html exists."
-            else
-              echo "❌ hello.html is missing!"
-              exit 1
-            fi
-  
+          if [ -f "hello.html" ]; then
+            echo "✅ hello.html exists."
+          else
+            echo "❌ hello.html is missing!"
+            exit 1
+          fi
       - name: Test hello.html in a local server
         run: |
-            # Start a simple HTTP server in background
-            python3 -m http.server 8000 &
-            sleep 2  # Give the server a second to start
-            # Test the file
-            curl --fail http://localhost:8000/hello.html
+          python3 -m http.server 8000 &
+          sleep 2
+          curl --fail http://localhost:8000/hello.html
         shell: bash
       - run: echo "🍏 This job's status is ${{ job.status }}."
